context.reaction.block_plugin.*:
  type: block.settings.[id]
  mapping:
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    uuid:
      type: uuid
    custom_id:
      type: string
    theme:
      type: string
    css_class:
      type: string
    context_id:
      type: string
    unique:
      type: integer
    context_mapping:
      type: sequence
      label: 'Block context'
      sequence:
        - type: string
    third_party_settings:
      type: string

reaction.plugin:
  type: mapping
  label: 'Reaction'
  mapping:
    id:
      type: string
      label: 'ID'
    negate:
      type: boolean
      label: 'Negate'
    uuid:
      type: uuid
    reaction_mapping:
      type: sequence
      label: 'Reaction assignments'
      sequence:
        type: string
    blocks:
      type: sequence
      label: 'Blocks'
      sequence:
        - type: context.reaction.block_plugin.[id]

condition.plugin:
  type: mapping
  label: 'Condition'
  mapping:
    id:
      type: string
      label: 'ID'
    negate:
      type: boolean
      label: 'Negate'
    uuid:
      type: uuid
    context_mapping:
      type: sequence
      label: 'Conditions'
      sequence:
        type: string
    view_inclusion:
      type: sequence
      label: 'View Inclusion'
      sequence:
        type: string
